// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkIgntc1-gp93I-vXOfgBa6J5LA0eulCE',
    appId: '1:146837610072:web:595d216ca219d9808df42d',
    messagingSenderId: '146837610072',
    projectId: 'dboxxo-6a039',
    authDomain: 'dboxxo-6a039.firebaseapp.com',
    storageBucket: 'dboxxo-6a039.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPjGQS5xlq0e132zsVbD8OIOmqrYip1Ek',
    appId: '1:146837610072:android:915d1fba9fb9e8008df42d',
    messagingSenderId: '146837610072',
    projectId: 'dboxxo-6a039',
    storageBucket: 'dboxxo-6a039.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4OK7Sjx2UCOd7wE6_jhjGmRKc5Vb0yOk',
    appId: '1:146837610072:ios:c97cf870436ed3928df42d',
    messagingSenderId: '146837610072',
    projectId: 'dboxxo-6a039',
    storageBucket: 'dboxxo-6a039.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4OK7Sjx2UCOd7wE6_jhjGmRKc5Vb0yOk',
    appId: '1:146837610072:ios:c97cf870436ed3928df42d',
    messagingSenderId: '146837610072',
    projectId: 'dboxxo-6a039',
    storageBucket: 'dboxxo-6a039.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

}